### ISSUE TITLE
SSL Error when querying for genes

### ISSUE THREAD

**Issue by jkanche** [cbg-ethz/rDGIdb#3] opened 2020-09-29 12:48 UTC
Hello,

The package fails when I try to query for a list of genes. 

a reproducible example, same as the example code for the `queryDGIdb` method

```
> genes <- c("XYZA", "TNF", "IL6", "IL8")
> result <- queryDGIdb(genes = genes)
Querying DGIDB...Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL: no alternative certificate subject name matches target host name 'dgidb.genome.wustl.edu'

```

**Comment by sdl002** [comment] 2020-09-29 15:06
Same issue, I believe the issue is due to the new https address for dgidb (now https://dgidb.org instead of https://dgidb.genome.wustl.edu). Unsure of a fix at this point, though I have emailed the developers directly.

**Comment by jkanche** [comment] 2020-09-29 15:40
I noticed the change in the API endpoints and tried to fix that in my fork, but it quite doesn't fix the issue

the url fix works for the example snippet from the earlier post. but if i change the gene names to a different list 

```
> library(rDGIdb)
> genes2 <- c("KRAS", "PIK3CA", "BRCA2")
> result <- queryDGIdb(genes = genes2)
Querying DGIDB...done!
 Error in (function (..., deparse.level = 1)  : 
  number of columns of matrices must match (see arg 2) 
```


traceback on the error 

```
 Error in (function (..., deparse.level = 1)  : 
  number of columns of matrices must match (see arg 2) 
6.
(function (..., deparse.level = 1) 
.Internal(rbind(deparse.level, ...)))(structure(c("KRAS", "KRAS", 
"KRAS", "KRAS", "KRAS", "KRAS", "KRAS", "KRAS", "KRAS", "KRAS", 
"KRAS", "KRAS", "KRAS", "KRAS", "KRAS", "KRAS", "KRAS", "KRAS",  ... 
5.
do.call(rbind, interactionList) at rDGIdbResult.R#50
4.
data.frame(do.call(rbind, interactionList), stringsAsFactors = FALSE) at rDGIdbResult.R#50
3.
setResultSummary(result) at rDGIdbResult.R#38
2.
setResultSummary(result) at queryDGIdb.R#115
1.
queryDGIdb(genes = genes2) 

```

**Comment by stekhoven** [comment] 2020-10-01 09:17
The DGIdb API has changed and we are working on an update which should soon be available through bioconductor. The github page will undergo the update in due course.

**Comment by thurnherr** [comment] 2020-10-01 19:48
An update of the package is now available in the development branch of Bioconductor ([rDGIdb devel branch](http://bioconductor.org/packages/devel/bioc/html/rDGIdb.html)), which will be released on October 28th, 2020. Let me know if you encounter any more issues while using the package.

**Closed as completed by thurnherr** 2020-10-01 19:48 UTC
